import type { ModelInfo } from "@/lib/types";

export const models: ModelInfo[] = [
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    description: "Strong general-purpose reasoning with reliable tool use and crisp output.",
    inputPricePer1k: 0.005,
    outputPricePer1k: 0.015,
    contextWindow: 128000,
    useCase: "Balanced assistant for most production workflows.",
    badge: "recommended",
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "anthropic",
    description: "Fast, polished writing with a very strong long-form reasoning profile.",
    inputPricePer1k: 0.003,
    outputPricePer1k: 0.015,
    contextWindow: 200000,
    useCase: "Drafting, analysis, and polished responses at scale.",
    badge: "accurate",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    description: "Large context and strong multimodal capabilities for complex tasks.",
    inputPricePer1k: 0.0035,
    outputPricePer1k: 0.012,
    contextWindow: 1000000,
    useCase: "High-context analysis and multimodal workflows.",
    badge: "value",
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    provider: "meta",
    description: "Open-weight model with strong throughput and flexible deployment options.",
    inputPricePer1k: 0.002,
    outputPricePer1k: 0.008,
    contextWindow: 128000,
    useCase: "Self-hosted and cost-sensitive deployments.",
    badge: "fast",
  },
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    provider: "mistral",
    description: "Efficient model with sharp instruction-following and competitive latency.",
    inputPricePer1k: 0.0025,
    outputPricePer1k: 0.01,
    contextWindow: 32768,
    useCase: "Low-latency product experiences and structured tasks.",
  },
];
