import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto py-16 px-4 animate-in">
      <Link href="/" className="text-sm text-text-secondary/50 hover:text-text-primary transition-colors inline-flex items-center gap-1 mb-6">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 18 9 12 15 6"/></svg>
        Home
      </Link>

      <h1 className="text-2xl font-bold mb-4">Terms of Service</h1>

      <div className="prose prose-sm max-w-none text-text-secondary/70 space-y-4 text-[14px] leading-relaxed">
        <p>Welcome to Nyayantar, a legal AI research assistant developed by Bizfy Solutions. By using this service, you agree to the following terms.</p>

        <h2 className="text-base font-semibold text-text-primary mt-6 mb-2">Use of Service</h2>
        <p>Nyayantar provides legal information for educational and research purposes only. It does not constitute legal advice, and should not be relied upon as a substitute for professional legal counsel.</p>

        <h2 className="text-base font-semibold text-text-primary mt-6 mb-2">Limitations</h2>
        <p>Responses are generated by AI and may contain inaccuracies. Always verify information with authoritative legal sources. For case-specific advice, consult a qualified legal professional.</p>

        <h2 className="text-base font-semibold text-text-primary mt-6 mb-2">Privacy</h2>
        <p>Your queries and conversations are processed to generate responses. See our <Link href="/legal/privacy" className="text-accent hover:underline">Privacy Policy</Link> for full details.</p>

        <h2 className="text-base font-semibold text-text-primary mt-6 mb-2">Contact</h2>
        <p>For questions about these terms, contact us at info@nyayantar.com.</p>
      </div>
    </div>
  )
}
